version: "2"
services:
  web:
    container_name: web
    environment:
      - ALLOW_OVERRIDE=true
    build: .
    ports: 
      - "80:80"
    volumes:
      - .:/var/www/html/
      - ./shared:/var/run/mysqld
      # - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
      # usar ip local 172.19.0.2 da maquina mariadb p/ conectar do host 
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./shared:/var/run/mysqld
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links: 
  #       - db:db
  #   ports:
  #       - 8008:80
  #   environment:
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: test
  #     MYSQL_ROOT_PASSWORD: test
      
# version: '2'
# services:
#   mariadb:
#     container_name: mariadb
#     image: 'bitnami/mariadb:latest'
#     environment:
#       - MARIADB_USER=bn_opencart
#       - MARIADB_DATABASE=bitnami_opencart
#       - ALLOW_EMPTY_PASSWORD=yes
#     volumes:
#       - 'mariadb_data:/bitnami'
#   opencart:
#     container_name: opencart
#     image: 'bitnami/opencart:latest'
#     environment:
#       - MARIADB_HOST=mariadb
#       - MARIADB_PORT_NUMBER=3306
#       - OPENCART_DATABASE_USER=bn_opencart
#       - OPENCART_DATABASE_NAME=bitnami_opencart
#       - OPENCART_HOST=localhost
#       - ALLOW_EMPTY_PASSWORD=yes
#     labels:
#       kompose.service.type: nodeport
#     ports:
#       - '80:80'
#       - '443:443'
#     volumes:
#       - 'opencart_data:/bitnami'
#     depends_on:
#       - mariadb
# volumes:
#   mariadb_data:
#     driver: local
#   opencart_data:
#     driver: local
